//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitGym.WS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityDetail
    {
        public int ActivityDetailId { get; set; }
        public int ActivityId { get; set; }
        public int QRepetition { get; set; }
        public int ActivityTypeId { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual ActivityType ActivityType { get; set; }
    }
}
