//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitGym.WS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public int FoodId { get; set; }
        public int DietId { get; set; }
        public string Name { get; set; }
        public int TypeMealId { get; set; }
        public int Quantity { get; set; }
        public int QuantityMeasurementId { get; set; }
        public string Description { get; set; }
        public decimal Calories { get; set; }
    
        public virtual Diet Diet { get; set; }
        public virtual QuantityMeasurement QuantityMeasurement { get; set; }
        public virtual TypeMeal TypeMeal { get; set; }
    }
}
