//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitGym.WS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FitGymEntities : DbContext
    {
        public FitGymEntities()
            : base("name=FitGymEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<ActivityDetail> ActivityDetail { get; set; }
        public virtual DbSet<ActivityType> ActivityType { get; set; }
        public virtual DbSet<BodyMeasurements> BodyMeasurements { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Diet> Diet { get; set; }
        public virtual DbSet<Establishment> Establishment { get; set; }
        public virtual DbSet<Evaluation> Evaluation { get; set; }
        public virtual DbSet<Food> Food { get; set; }
        public virtual DbSet<Goal> Goal { get; set; }
        public virtual DbSet<GymCompany> GymCompany { get; set; }
        public virtual DbSet<PersonalTrainer> PersonalTrainer { get; set; }
        public virtual DbSet<QuantityMeasurement> QuantityMeasurement { get; set; }
        public virtual DbSet<Subscription> Subscription { get; set; }
        public virtual DbSet<SubscriptionType> SubscriptionType { get; set; }
        public virtual DbSet<TypeMeal> TypeMeal { get; set; }
    }
}
